Задача 1 - Сложение и изменение формы массивов:

● Создайте два одномерных массива из случайных целых чисел от 1 до 10.

● Выполните поэлементное сложение этих двух массивов.

● Измените форму полученного массива на матрицу 2x5.

● Посчитайте среднее значение

In [5]:
import numpy as np
import random
arr1=np.random.randint(1,11,10)
arr2=np.random.randint(1,11,10)
sum=arr1+arr2
print(arr1)
print(arr2)
print(sum)

[ 4  6 10  9  6  3  3  9  1  4]
[ 4  9  2  2 10  6  9  4  6  5]
[ 8 15 12 11 16  9 12 13  7  9]


In [6]:
r_matrix=sum.reshape(2,5)
mean_v=np.mean(r_matrix)
print(r_matrix)
print(mean_v)

[[ 8 15 12 11 16]
 [ 9 12 13  7  9]]
11.2


Задача 2 - Работа со срезами и формами:

● Создайте массив размером 3x3 и выведите его первую строку и первый столбец.

● Измените форму массива с помощью функции reshape и выведите его новую форму.

● Используйте функцию flatten, чтобы преобразовать массив в одномерный.

In [19]:
arr2d=np.random.randint(1,11,size=(3,3))
print(arr2d)
print(arr2d[0])
print(arr2d[:,0])

[[ 1  9  4]
 [10  8  5]
 [ 9  4  4]]
[1 9 4]
[ 1 10  9]


In [27]:
r2_matrix=arr2d.reshape(1,9)# из 3х3 матрицы можно сделать только матрицу на (1,9)
print(r2_matrix)
f_matrix=arr2d.flatten()
print(f_matrix)

[[ 1  9  4 10  8  5  9  4  4]]
[ 1  9  4 10  8  5  9  4  4]


Задача 3 - Генерация массива и объединение столбцов:

● Создайте двумерный массив размером 4x3 с случайными целыми числами от 1 до 10.

● Объедините столбцы этого массива в один столбец с использованием vstack.

In [11]:
arr3=np.random.randint(1,11,size=(4,3))
print(arr3)
arr4 = arr3.reshape(-1) # Преобразуем массив в одномерный массив
print(arr4)
stacked_array = np.vstack(arr4) # Используем vstack для объединения одномерных массивов
print(stacked_array)

[[5 8 8]
 [2 2 3]
 [1 4 4]
 [7 8 8]]
[5 8 8 2 2 3 1 4 4 7 8 8]
[[5]
 [8]
 [8]
 [2]
 [2]
 [3]
 [1]
 [4]
 [4]
 [7]
 [8]
 [8]]


Задача 4 - Генерация массива и индексирование:

● Создайте массив из 9 случайных чисел от 1 до 30.

● Найдите индекс максимального значения в массиве и выведите это значение.

In [39]:
arr4=np.random.randint(1,31,size=9)
print(arr4)
max_index = np.argmax(arr4)
print(max_index)

[26 23 16  1 15 22 15 16  9]
0


Задача 5 - Операции над массивами:

● Создайте два массива, каждый размером 2x2, состоящих из случайных целых чисел от 1 до 5.

● Транспонируйте один из массивов.

● Сложите транспонированный массив с другим массивом.

In [40]:
arr5=np.random.randint(1,6,size=(2,2))
arr6=np.random.randint(1,6,size=(2,2))
print(arr5)
print(arr6)

[[5 1]
 [5 1]]
[[4 3]
 [5 5]]


In [43]:
t_matrix=arr6.transpose()
print(t_matrix)

[[4 5]
 [3 5]]


In [44]:
c=arr5+t_matrix
print(c)

[[9 6]
 [8 6]]
