1. Основы NumPy: Создайте массив NumPy из списка, содержащего числа от 1 до 10. Выведите этот массив.

In [4]:
import numpy as np

In [5]:
arr1d=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr1d)

[ 1  2  3  4  5  6  7  8  9 10]


2. Операции с массивами: Создайте два массива NumPy: первый с элементами от 1 до 5, второй - с элементами от 6 до 10. Выполните поэлементное сложение этих массивов.

In [6]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
s=arr1+arr2
print(s)

[ 7  9 11 13 15]


3. Индексация и срезы: Создайте одномерный массив из первых 10 целых чисел. Выведите все четные элементы этого массива (используйте индексацию также как для списков).

In [7]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
for i in range(len(arr1d)):
    if arr1d[i]%2==0:
        print(arr1d[i])

2
4
6
8
10
