1. Создание массивов:

a. Создайте одномерный массив из 5 целых чисел.

b. Создайте трехмерный массив размером 3x3х3, то есть должно быть три матрицы с размером  3х3.

с. Создайте одномерный массив из 8 случайных целых чисел в диапазоне от 1 до 20.

In [3]:
import numpy as np
import random 
#a
arr1=np.array([1,2,4,5,6])
#b
arr2 = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                     
                     [[10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18]],
                     
                     [[19, 20, 21],
                      [22, 23, 24],
                      [25, 26, 27]]])
#c
arr3=np.random.randint(1, 20, 8)

In [11]:
print(arr1)

[1 2 4 5 6]


In [18]:
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [15]:
print(arr3)

[ 2 11 16 17 17 18  7  1]


2. Работа с элементами массивами

a. Найдите и выведите второй элемент вашего одномерного массива.

b. Найдите и выведите значение во второй строке и третьем столбце  первой матрицы вашего трехмерного массива.

с. Поменяйте любое  значение 2 матрицы трехмерного массива

In [16]:
#a
for i in range(len(arr1)):
    if i==1:
        print(arr1[i])

2


In [19]:
#b
print(arr2[0, 1, 2])

6


In [20]:
#c
arr2[1, 2, 1] = 100

In [21]:
arr2

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  11,  12],
        [ 13,  14,  15],
        [ 16, 100,  18]],

       [[ 19,  20,  21],
        [ 22,  23,  24],
        [ 25,  26,  27]]])

3. Работа со срезами

a. Создайте одномерный массив от 1 до 9. Используя срезы, выведите элементы от 3 до 9

b. Создайте двумерную матрицу. Используя срезы, выведите следующие подматрицы:

            Первые три строки матрицы.

            Последний столбец матрицы.

In [23]:
#a
arr1=np.arange(1,10)

In [24]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr1[3:10]

array([4, 5, 6, 7, 8, 9])

In [4]:
#b
arr2=np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12],[4,8,6,10]])

In [39]:
arr2

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8,  6, 10]])

In [44]:
arr2[:3]

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [6]:
arr2[:,-1]

array([ 4,  8, 12, 10])

In [17]:
pip install opencv-python


In [20]:
import cv2

image = cv2.imread('pic png.png')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # Convert from BGR to RGB

import numpy as np
import matplotlib.pyplot as plt
from skimage import data, color

blue_white_image = np.copy(image)
blue_white_image[:, :, 0] = 0 # Red channel
blue_white_image[:, :, 1] = 0 # Green channel
bright_areas = blue_white_image[:, :, 2] > 120
blue_white_image[bright_areas, 2] = 255

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title('Original Image')
plt.axis('off')
plt.subplot(1, 2, 2)
plt.imshow(blue_white_image)
plt.title('Blue and White Image')
plt.axis('off')

plt.show()

error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
